"""empty message

Revision ID: f99c7f8c413e
Revises: 7391ffab9127
Create Date: 2025-08-05 10:06:38.340164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f99c7f8c413e"
down_revision: Union[str, None] = "7391ffab9127"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel_proposal", sa.Column("channel_username", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channel_proposal", "channel_username")
    # ### end Alembic commands ###
