"""empty message

Revision ID: d197d8b62037
Revises: 9b0324cbccd7
Create Date: 2025-08-05 11:13:52.449406

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d197d8b62037"
down_revision: Union[str, None] = "9b0324cbccd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel_proposal", sa.Column("channel_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(None, "channel_proposal", "channel", ["channel_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "channel_proposal", type_="foreignkey")
    op.drop_column("channel_proposal", "channel_id")
    # ### end Alembic commands ###
