"""empty message

Revision ID: 7391ffab9127
Revises: 1c3047671965
Create Date: 2025-08-05 09:37:10.633574

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7391ffab9127"
down_revision: Union[str, None] = "1c3047671965"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("invite_link", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("last_parsed_message_id", sa.BigInteger(), nullable=True),
        sa.Column("last_checked", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_channel_id"), "channel", ["id"], unique=False)
    op.create_index(op.f("ix_channel_username"), "channel", ["username"], unique=False)
    op.create_table(
        "channel_proposal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_proposal_id"), "channel_proposal", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_channel_proposal_id"), table_name="channel_proposal")
    op.drop_table("channel_proposal")
    op.drop_index(op.f("ix_channel_username"), table_name="channel")
    op.drop_index(op.f("ix_channel_id"), table_name="channel")
    op.drop_table("channel")
    # ### end Alembic commands ###
