"""empty message

Revision ID: 3ef547f372b8
Revises: ea98886c896d
Create Date: 2025-09-04 11:06:42.738166

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ef547f372b8"
down_revision: Union[str, None] = "ea98886c896d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_whitelist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_whitelist_telegram_id"),
        "user_whitelist",
        ["telegram_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_user_whitelist_username"), "user_whitelist", ["username"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_whitelist_username"), table_name="user_whitelist")
    op.drop_index(op.f("ix_user_whitelist_telegram_id"), table_name="user_whitelist")
    op.drop_table("user_whitelist")
    # ### end Alembic commands ###
