"""empty message

Revision ID: 4dba17fe6344
Revises: 281e61a382ab
Create Date: 2025-08-05 11:48:21.387075

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4dba17fe6344"
down_revision: Union[str, None] = "281e61a382ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channel", sa.Column("channel_username", sa.String(), nullable=True))
    op.drop_index("ix_channel_username", table_name="channel")
    op.create_index(
        op.f("ix_channel_channel_username"),
        "channel",
        ["channel_username"],
        unique=False,
    )
    op.drop_column("channel", "username")
    op.drop_column("channel", "channel_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel",
        sa.Column("channel_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "channel",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_channel_channel_username"), table_name="channel")
    op.create_index("ix_channel_username", "channel", ["username"], unique=False)
    op.drop_column("channel", "channel_username")
    # ### end Alembic commands ###
