"""empty message

Revision ID: c14ea3a9588c
Revises:
Create Date: 2025-09-01 21:46:26.209429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c14ea3a9588c"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "channel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_username", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("invite_link", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=False),
        sa.Column("last_parsed_message_id", sa.BigInteger(), nullable=True),
        sa.Column("last_checked", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_channel_username"),
        "channel",
        ["channel_username"],
        unique=False,
    )
    op.create_index(op.f("ix_channel_id"), "channel", ["id"], unique=False)
    op.create_table(
        "keyword",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_keyword_id"), "keyword", ["id"], unique=False)
    op.create_index(op.f("ix_keyword_text"), "keyword", ["text"], unique=False)
    op.create_table(
        "telethon_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("api_id", sa.String(), nullable=False),
        sa.Column("api_hash", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_authorized", sa.Boolean(), nullable=True),
        sa.Column("session_string", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_telethon_account_id"), "telethon_account", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_telethon_account_name"), "telethon_account", ["name"], unique=False
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_operator", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_telegram_id"), "user", ["telegram_id"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "channel_proposal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_username", sa.String(), nullable=True),
        sa.Column("operator_id", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["user.telegram_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_channel_proposal_id"), "channel_proposal", ["id"], unique=False
    )
    op.create_table(
        "keyword_proposal",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=True),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("admin_comment", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keyword.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_keyword_proposal_id"), "keyword_proposal", ["id"], unique=False
    )
    op.create_table(
        "post",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("channel_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("html_text", sa.Text(), nullable=True),
        sa.Column("media_type", sa.String(), nullable=True),
        sa.Column("media_file_id", sa.String(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["channel_id"],
            ["channel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_post_id"), "post", ["id"], unique=False)
    op.create_table(
        "post_keyword_match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keyword.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_post_keyword_match_id"), "post_keyword_match", ["id"], unique=False
    )
    op.create_table(
        "post_processing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_post_processing_id"), "post_processing", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_post_processing_id"), table_name="post_processing")
    op.drop_table("post_processing")
    op.drop_index(op.f("ix_post_keyword_match_id"), table_name="post_keyword_match")
    op.drop_table("post_keyword_match")
    op.drop_index(op.f("ix_post_id"), table_name="post")
    op.drop_table("post")
    op.drop_index(op.f("ix_keyword_proposal_id"), table_name="keyword_proposal")
    op.drop_table("keyword_proposal")
    op.drop_index(op.f("ix_channel_proposal_id"), table_name="channel_proposal")
    op.drop_table("channel_proposal")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_telegram_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_telethon_account_name"), table_name="telethon_account")
    op.drop_index(op.f("ix_telethon_account_id"), table_name="telethon_account")
    op.drop_table("telethon_account")
    op.drop_index(op.f("ix_keyword_text"), table_name="keyword")
    op.drop_index(op.f("ix_keyword_id"), table_name="keyword")
    op.drop_table("keyword")
    op.drop_index(op.f("ix_channel_id"), table_name="channel")
    op.drop_index(op.f("ix_channel_channel_username"), table_name="channel")
    op.drop_table("channel")
    # ### end Alembic commands ###
