"""empty message

Revision ID: 130c29224118
Revises: c14ea3a9588c
Create Date: 2025-09-02 09:38:11.512710

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "130c29224118"
down_revision: Union[str, None] = "c14ea3a9588c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "post_processing", sa.Column("notify_chat_id", sa.BigInteger(), nullable=True)
    )
    op.add_column(
        "post_processing", sa.Column("notify_message_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "post_processing",
        sa.Column("notify_sent_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post_processing", "notify_sent_at")
    op.drop_column("post_processing", "notify_message_id")
    op.drop_column("post_processing", "notify_chat_id")
    # ### end Alembic commands ###
