"""empty message

Revision ID: c29c073ee5dd
Revises: a9e1d970e1ae
Create Date: 2025-08-05 10:48:18.279811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c29c073ee5dd"
down_revision: Union[str, None] = "a9e1d970e1ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "channel_proposal_operator_id_fkey", "channel_proposal", type_="foreignkey"
    )
    op.drop_constraint(
        "channel_proposal_channel_id_fkey", "channel_proposal", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "channel_proposal", "user", ["operator_id"], ["telegram_id"]
    )
    op.drop_column("channel_proposal", "channel_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "channel_proposal",
        sa.Column("channel_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "channel_proposal", type_="foreignkey")
    op.create_foreign_key(
        "channel_proposal_channel_id_fkey",
        "channel_proposal",
        "channel",
        ["channel_id"],
        ["id"],
    )
    op.create_foreign_key(
        "channel_proposal_operator_id_fkey",
        "channel_proposal",
        "user",
        ["operator_id"],
        ["id"],
    )
    # ### end Alembic commands ###
