version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: telegram_monitoring_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_monitoring_bot
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - MODE=${MODE}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
      - SUPER_ADMIN=${SUPER_ADMIN}

volumes:
  postgres_data:
